In [0]:
%tensorflow_version 2.x

In [0]:
import numpy as np
import tensorflow as tf

In [0]:
#prepare data for predicting
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_features = 1
n_steps = 3

In [0]:
#spilit sequence into the training dataset
def spilt_seq(sequence, history_size):
    X, y = [], []
    for i in range(len(sequence)):
        start_ix, end_ix = i, i+history_size
        if end_ix < len(sequence):
            X.append(sequence[start_ix : end_ix])
            y.append(sequence[end_ix])
    return np.array(X), np.array(y)


In [46]:
X, y = spilt_seq(raw_seq, n_steps)
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [0]:
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [48]:
#build a basic LSTM model, picking up proper activation function is important
model = tf.keras.models.Sequential()
#model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True, activation='relu'), input_shape=(n_steps, n_features)))
#model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(tf.keras.layers.Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=200, verbose=1)


Train on 6 samples
Epoch 1/200
6/6 [==============================] - 2s 253ms/sample - loss: 4424.2817
Epoch 2/200
6/6 [==============================] - 0s 2ms/sample - loss: 4351.2847
Epoch 3/200
6/6 [==============================] - 0s 2ms/sample - loss: 4278.6118
Epoch 4/200
6/6 [==============================] - 0s 1ms/sample - loss: 4206.0981
Epoch 5/200
6/6 [==============================] - 0s 1ms/sample - loss: 4133.1646
Epoch 6/200
6/6 [==============================] - 0s 1ms/sample - loss: 4059.7683
Epoch 7/200
6/6 [==============================] - 0s 1ms/sample - loss: 3986.1584
Epoch 8/200
6/6 [==============================] - 0s 1ms/sample - loss: 3912.5276
Epoch 9/200
6/6 [==============================] - 0s 1ms/sample - loss: 3839.0032
Epoch 10/200
6/6 [==============================] - 0s 1ms/sample - loss: 3765.4519
Epoch 11/200
6/6 [==============================] - 0s 1ms/sample - loss: 3692.7385
Epoch 12/200
6/6 [==============================] - 0s 1ms/sampl

In [49]:
model

In [50]:
#have a test
X_test = np.array([70, 80, 90])
X_test = X_test.reshape((1, n_steps, n_features))
y_test = model.predict(X_test)
print(y_test)

[[102.06363]]
