In [0]:
%tensorflow_version 2.x

In [0]:
import numpy as np
import tensorflow as tf

In [0]:
#prepare data for predicting
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_features = 1
n_steps = 3

In [0]:
#spilit sequence into the training dataset
def spilt_seq(sequence, history_size):
    X, y = [], []
    for i in range(len(sequence)):
        start_ix, end_ix = i, i+history_size
        if end_ix < len(sequence):
            X.append(sequence[start_ix : end_ix])
            y.append(sequence[end_ix])
    return np.array(X), np.array(y)


In [255]:
X, y = spilt_seq(raw_seq, n_steps)
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [0]:
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [257]:
#build a basic LSTM model, picking up proper activation function is important
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(tf.keras.layers.Dense(1))
model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=200, verbose=1)


Train on 6 samples
Epoch 1/200
6/6 [==============================] - 2s 305ms/sample - loss: 3132.7188
Epoch 2/200
6/6 [==============================] - 0s 1ms/sample - loss: 2981.3557
Epoch 3/200
6/6 [==============================] - 0s 1ms/sample - loss: 2834.0081
Epoch 4/200
6/6 [==============================] - 0s 1ms/sample - loss: 2690.4915
Epoch 5/200
6/6 [==============================] - 0s 1ms/sample - loss: 2549.4148
Epoch 6/200
6/6 [==============================] - 0s 1ms/sample - loss: 2411.4746
Epoch 7/200
6/6 [==============================] - 0s 1ms/sample - loss: 2276.6116
Epoch 8/200
6/6 [==============================] - 0s 1ms/sample - loss: 2144.6016
Epoch 9/200
6/6 [==============================] - 0s 1ms/sample - loss: 2015.2661
Epoch 10/200
6/6 [==============================] - 0s 1ms/sample - loss: 1888.7891
Epoch 11/200
6/6 [==============================] - 0s 2ms/sample - loss: 1764.6891
Epoch 12/200
6/6 [==============================] - 0s 1ms/sampl

In [258]:
model

In [259]:
#have a test
X_test = np.array([70, 80, 90])
X_test = X_test.reshape((1, n_steps, n_features))
y_test = model.predict(X_test)
print(y_test)

[[101.28506]]
